name: 'workflow-conclusion'

description: 'This action outputs the outcomes of jobs within the workflow.'

inputs:
  github-token:
    description: Secret GitHub API token to use for making API requests.
    default: ${{ github.token }}
    required: true
  fallback-conclusion:
    description: 'The fallback conclusion to use'
    required: false
    default: skipped

outputs:
  conclusion:
    description: Workflow conclusion

runs:
  using: 'node12'
  main: 'dist/index.js' # Can also be a relative path to the js file you want executed
